[workspace]
members = [
  "src/costanza-mid",
  "src/costanza-eui"
]

[patch.crates-io]
serialport = { git = "https://github.com/mf-dhadley/serialport-rs.git", branch = "unpin-version" }
glutin = { git = "https://github.com/dadleyy/glutin.git", branch = "pixelformat-changes" }
