[http]
addr="0.0.0.0:8081"
domain="0.0.0.0"
auth_complete_uri="http://0.0.0.0:8338/welcome"

[http.session]
jwt_secret=""
redis_addr=""

[http.oauth]
auth_client_id=""
auth_client_secret=""
management_client_id=""
management_client_secret=""
redirect_uri="http://0.0.0.0:8081/auth/complete"
domain=""

[serial]
device="/dev/pts/5"
baud=115200

[timing]
broadcast_interval=1
